---
abstract: 'Perl interface for the RAMBrick search thingie https://github.com/jackdoe/brick/tree/master/bricks/RAMBrick'
author:
  - 'Borislav Nikolov <jack@sofialondonmoskva.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-Brick-RAM-Query
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 2.145
  Data::MessagePack: 0.48
  Data::MessagePack::Stream: 0.07
  IO::Select: 1.17
  Test::Exception: 0.32
  Time::HiRes: 1.9725
version: 0.03
